server:
  port: 8888

spring:
  application:
    name: springboot-mybatis-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 3000ms
      quiet-period: 2999ms

